version: '3.8'

services:
  hyblab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "hyblab-server"
    ports:
      - "80:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules